Updates to Guidance Note Submission Checklist, and Reviewer Feedback Checklist
worldbank/dime-standards pull request #54
Opened 2024-09-19 02:33 UTC by Avnish95

Guidance note is now in GitHub markdown, and aligned with the reproducibility verification guidelines, along with the submission checklist, and reviewer feedback checklist

2024-09-19 17:44 UTC, Avnish95 commented
Hi @mariaruth, requesting your review on the updates to the Peer Code Review guidance note, package submission checklist, and the feedback checklist based on comments from Mer, Luise, Roshni, Ankriti, Mahin, as well as the general idea of aligning them with the reproducibility guidelines.

Thanks so much!

2024-09-26 07:43 UTC, mariaruth commented on dime-coding-standards/checklists/tex/reviewer_feedback_checklist.tex
> +        \textbf{NOTE:} Your deliverable from this exercise will be  \href{https://survey.wb.surveycto.com/collect/code_review_summary?caseid=}{this detailed form} which replicates the checklist below
```suggestion
        \textbf{NOTE:} Your deliverable from this exercise will be  \href{https://survey.wb.surveycto.com/collect/code_review_summary?caseid=}{this online survey form} which replicates the checklist below.
```

2024-09-26 07:46 UTC, mariaruth commented on dime-coding-standards/checklists/tex/reviewer_feedback_checklist.tex
Checkbox about tables: suggest wording this as "Tables and charts are exported (preferably as raw text files)"

2024-09-26 07:47 UTC, mariaruth commented on dime-coding-standards/checklists/tex/reviewer_feedback_checklist.tex
> +        \textit{\textbf{Next step:}} If you received data as part of the peer review package, attempt to run the code files. Ideally, you will be able to do so by changing only the top-level director
```suggestion
        \textit{\textbf{Next step:}} If you received data as part of the peer review package, attempt to run the code files. Ideally, you will be able to do so by changing only the top-level directory in the main script. 
```

2024-09-26 07:48 UTC, mariaruth commented on dime-coding-standards/checklists/tex/reviewer_feedback_checklist.tex
> +        \textit{\textbf{Next step:}} If you received data as part of the peer review package, attempt to run the code files. Ideally, you will be able to do so by changing only the top-level director
not necessary to link to form again, potentially confusing because makes it seem like it was a different form than linked at the top of the page

2024-09-26 07:51 UTC, mariaruth commented on dime-coding-standards/checklists/tex/reviewer_feedback_checklist.tex
>          \item[] \dimeCheckBox{Naming practices}
not clear what this means

2024-09-26 07:51 UTC, mariaruth commented on dime-coding-standards/checklists/tex/reviewer_feedback_checklist.tex
>          \item[] \dimeCheckBox{Naming practices}
master script ---> change to main script

2024-09-26 07:54 UTC, mariaruth commented on dime-coding-standards/checklists/tex/code-review-package-checklist
> +              \item[] \dimeCheckBox{A \textbf{main script} that the reviewer can use to run all code after changing only the top-level directory. \href{https://github.com/worldbank/wb-reproducible-re
should link to template r script too

2024-09-26 07:55 UTC, mariaruth commented on dime-coding-standards/guidance_note_peer_code_review.md
> +working on code are expected to participate, and any Bank staff or consultant who would like to
```suggestion
working on code are expected to participate regularly, and any Bank staff or consultant who would like to
```

2024-09-26 07:58 UTC, mariaruth commented on dime-coding-standards/guidance_note_peer_code_review.md
> +    - As part of this step, teams should identify and indicate which tasks they want reviewed. Examples include data cleaning, indicator construction, analysis, sampling and randomization, high-frequ
This is important. How do reviewers know what tasks their partner wants done? and shouldn't the checklist they follow depend on the request from their partners? Currently, looks like all reviewers should fill out all aspects of the same checklist and i think that's quite different than the spirit of the exercise. Clarify this in guidance note but also in workflow.

2024-09-26 07:59 UTC, mariaruth commented on dime-coding-standards/guidance_note_peer_code_review.md
> +    - Verifying computational reproducibility consists of ensuring that the reviewer can reproduce exactly the outputs (statistical tables and/or data visualizations) in the submitted package by runn
```suggestion
    - Verifying computational reproducibility consists of ensuring that the reviewer can reproduce exactly the outputs (statistical tables and/or data visualizations) in the submitted package by running the exact package of code and data shared with the reviewer.
```

2024-09-26 08:00 UTC, mariaruth commented on dime-coding-standards/guidance_note_peer_code_review.md
> +   - A hybrid **kickoff session** to outline the process, and assign code review partners
shall we note this is optional for people who have participated before?

2024-09-26 08:01 UTC, mariaruth commented on dime-coding-standards/guidance_note_peer_code_review.md
> +   - A hybrid **group review session** with technical support from DIME Analytics. Pairs work together, and answer questions to allow each other to review their submitted code.
Mention here that it's most effective when teams can work together, in-person, on the review, in order to answer questions in real-time.

2024-09-26 08:23 UTC, mariaruth requested changes
@Avnish95 i left some specific comments throughout. overall, i think we still need a better workflow around what tasks people want to be reviewed and guide reviewers to the appropriate checklists, see specific thoughts below

_code review signup form_

- need to update link to guidance note
- align list of tasks to be reviewed to match exactly with the checklists, and include computational reproducibility. then, this task list should be used to point reviewers to the exact checklists they should fill out, and the same tasks should be on the reviewer submission form so they are asked to enter information for only the relevant checklists. 

_code review submission form_

- comments here follow my comments on the sign up form. 
- change "what tasks was the code performing" to "what tasks did you review" and align list exactly to checklists, include computational reproducibility
- there's a note that says "(please make sure the submitted package includes a [completed submission checklist)](https://github.com/worldbank/dime-standards/blob/master/dime-coding-standards/checklists/Peer%20Code%20Review%20Submission%20Checklist.pdf)" -- why is this necessary? aren't the questions captured in the submission form? i understood the pdfs to be for reviewers to use but not to be submitted.
- actually, what is the point of the whole question "Which of the following does the shared package include: (please make sure the submitted package includes a [completed submission checklist)]"?
- ok, i see that we are asking reviewers to upload pdfs of the checklists. why though? why not have this info entered in a form just like they do for the main checklist? that way we would have data readily available, and facilitates exchange of reviewed information. 
- rather than having separate flow about data just include reproducibility verification as a task in the list

2024-09-26 08:25 UTC, mariaruth commented
One more point that got cut off: i think it needs to be clearer in the guidance note that all reviewers fill out the checklist for overall code feedback (from which we'll remove reproducibility) and then fill out other checklists depending on the tasks requested for review.

2024-10-03 19:43 UTC, merged